version: '3.4'
services:

  db:
    platform: "linux/amd64"
    image: mysql:8.0-oracle
    environment:
      MYSQL_DATABASE: superPriceDB
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  api:
    platform: "linux/amd64"
    build: backend/
    image: 854889991192.dkr.ecr.ap-southeast-2.amazonaws.com/superprice:superpriceg1
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: jdbc:mysql://localhost:3306/superprice
      spring.datasource.driverClassName: com.mysql.cj.jdbc.Driver
      spring.datasource.username: sa
      spring.datasource.password: password
    depends_on:
      - db

  web:
    platform: "linux/amd64"
    build: frontend/
    ports:
      - "3000:3000"
    environment:
      API_URL: "http://api:8080"
    depends_on:
      - api

  adminer:
    platform: "linux/amd64"
    image: adminer
    restart: always
    ports:
      - "9000:8080"
volumes:
  db_data: